kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
    anonymous:
        enabled: true
authorization:
        mode: Webhook
clusterDomain: "cluster.local"
clusterDNS:
  - "10.250.0.10"
runtimeRequestTimeout: "15m"
tlsCertFile: "/var/lib/kubelet/worker-1.pem"
tlsPrivateKeyFile: "/var/lib/kubelet/worker-1-key.pem"
authentication:
    x509:
        clientCAFile: /var/lib/kubelet/ca.pem
